// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukckzfdjewicusdfwciv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrY2t6ZmRqZXdpY3VzZGZ3Y2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTU2NjAsImV4cCI6MjA2NzM3MTY2MH0.NxahFZJJvpjkV8xf5Bn30gemGPdH4A8R7wN1vGJueCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});